### ISSUE TITLE
go test ./... has failures

### ISSUE THREAD

**Issue by lukebayes** [dotchain/dots#17]
Just from the failure messages, it  like tests might be reaching out to the network or at least, prod AWS libraries might not be getting insulated from the test env.

[result.txt](https://github.com/dotchain/dots/files/1934048/result.txt)

Haven't really looked into the issues at all yet, just digging around and letting you know!

:-)

**Comment by rameshvk** [comment]
Ah, I recall the issue.  I was looking for fakes for the dbs and S3 but only found one for S3 (mentioned in [Contributing.md](https://github.com/dotchain/dots/blob/master/CONTRIBUTING.md)) but don't think I found one for the rest. 

Anyway I was supposed to put these tests under a compiler flag but looks like I didn't get around to it.  Let me use this issue to do that.  Meanwhile, I suggest running `go test log/ journal/` (**log** and **journal** are the two top level services)

**Comment by rameshvk** [comment]
(I did build fakes for the storage interfaces but also have e2e tests for the individual databases to ensure that the SQL syntax and such are right -- those are the tests that fail here)
